### PR TITLE
Creditor Header should also list creditor_identifier

### PR DESCRIPTION
**Pull request by dolarsrg**
Creditor Header should also list creditor_identifier information as detailed in https://github.com/dolarsrg/sepa_king/blob/master/lib/schema/pain.008.001.02.xsd

### CODE REVIEW

**Comment by josegrad** [comment]
Strange I get 0.4.0 but these changes don't get in.

**Comment by ledermann** [comment]
@josegrad: This PR is not merged yet because it breaks the tests.

**Comment by josegrad** [comment]
@ledermann: Yeah true, didn't noticed I traveled to a different fork while following this.
Hmm. I'm just facing the same issue with a Spanish bank.

**Comment by ledermann** [comment]
Closed by #44

**Pull request closed without merging**
